### ISSUE TITLE
Be on Powered with Faust page ?

### ISSUE THREAD

**Issue by sletz** [plule/theremotion#3]
Great project ! 
Would you be interested to be on the [Powered By Faust](https://faust.grame.fr/community/made-with-faust/) page ? If yes do you have a more complete description of the project and screenshot? 
Are you this [Pierre Lulé](https://fr.linkedin.com/in/pierre-lulé-094b298a?original_referer=) ?

**Comment by sletz** [comment]
>  We are nearly neighbours, a live demo some day!

Yes that would be great ! And also discussing about Faust/Rust connections where you have a much larger experience than us ! 
Free free to connect to Faust Slack or Discords, see https://faust.grame.fr/community/help/.

**Comment by plule** [comment]
@sletz I've finally settled on a name, and I've update the readme including an introductory paragraph and a screenshot. Still need a proper demo, to have a very nice presentation of the project though.

Let me know if this is all you need for the Powered By Faust page!

**Comment by sletz** [comment]
Perfect I'll add it ASAP.

**Comment by sletz** [comment]
Done here: https://faust.grame.fr/community/made-with-faust/#theremotion.

**Comment by plule** [comment]
Nice, thank you!
