### ISSUE TITLE
Make left and right hand assignment configurable

### ISSUE THREAD

**Issue by jjdeprisco** [plule/theremotion#46]
In a traditional theremin, the left hand is volume and the right hand is pitch. In your current configuration, this is reversed and not intuitive for most theremin players. Best to make this configurable at the very least.

**Comment by plule** [comment]
Incoming soon! In the last changes (not yet released), the pitch is now controlled horizontally like a theremin, next step is to add the ability to invert hands.

**Comment by jjdeprisco** [comment]
Very cool. If you need someone to help with testing, let me know.

**Comment by plule** [comment]
@jjdeprisco Hey there, the main branch now has a right handed mode. I just have to do some presets before making a new release, but if you want to try it out already, you can get the build here: https://github.com/plule/theremotion/suites/9518334401/artifacts/451974182

Maybe don't use the .msi in there, just the theremotion.zip, the installer has a fake 0.0.0.0 version, maybe it can do annoying stuff

**Comment by plule** [comment]
Version `v1.2.0` has it.

**Comment by jjdeprisco** [comment]
Thanks. So far so good!
